"""
Django settings for RQMT project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%w46u8q!cbtc%32h_n25!s6ikwf_s-26f2xxg8n29hx@)3(n7v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1", "10.8.143.111"]


# Application definition

INSTALLED_APPS = [
    #my apps
    'dashboard',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #libs
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'RQMT.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'RQMT.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }

    # 'default':{
    #     'NAME':'ASMTransducer',
    #     'ENGINE':'sql_server.pyodbc',
    #     'Trusted_Connection':'yes',
    #     # 'HOST':'atssv008',
    #     'HOST':'(localdb)\Local',
    #     'Trusted_Connection':'yes',
    #     'USER': 'test123',
    #     'PASSWORD': 'Testing!12345678',
    #     'DRIVER':'ODBC Driver 13 for SQL Server',
    #     'OPTION':{
    #               'MARS_Connection': True,}
    # },
    'default':{
        'NAME':'ASMTransducer',
        'ENGINE':'sql_server.pyodbc',
        'Trusted_Connection':'yes',
        'HOST':'atssv008',
        'Trusted_Connection':'yes',
        'USER': 'ASMTransducerUser',
        'PASSWORD': '123456',
        'DRIVER':'ODBC Driver 13 for SQL Server',
        'OPTION':{
                  'MARS_Connection': True,}
    },

    'db_asmuser':{
        'NAME':'asmuser',
        'ENGINE':'sql_server.pyodbc',
        'HOST':'aaants45',
        'USER': 'fracas_user',
        'PASSWORD': 'fracasgetdata',
        'OPTION':{
            'driver':'ODBC Driver 13 for SQL Server',
            'MARS_Connection': True,
            }
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Singapore'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_ROOT=os.path.join(BASE_DIR,'static/dist')
STATIC_URL = '/static/'

STATICFILES_DIRS=(
    os.path.join(BASE_DIR,'static').replace('\\','/'),
)

EXCEL_PATH = "D:\work\Requirement Management\\"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
